name: movie-db
recipe: laravel
config:
  php: '7.3'
  via: apache:2.4
  webroot: public
  database: mysql:5.7
  cache: none
  xdebug: false
services:
  appserver:
    build:
      - composer install
    run:
      - cp .env.example .env
      - php artisan key:generate
      - php artisan migrate
  database:
    portforward: 7650
  node:
    type: node:11
    build:
      - npm install
    command:
      - npm run dev
tooling:
  node:
    service: node
  npm:
    service: node
  artisan:
    cmd: "php artisan"
